---
version: "3"
services:
  db:
    build: ./db
    image: speedtest-meter:db
    ports:
      - 8086:8086
    volumes:
      - ./data/db:/var/lib/influxdb
  probe:
    build: ./probe
    image: speedtest-meter:probe
    links:
      - db
    depends_on:
      - db
  web:
    build: ./web
    image: speedtest-meter:web
    environment:
      - GF_SERVER_ROOT_URL=http://localhost
      - GF_AUTH_ANONYMOUS_ENABLED=true
    links:
      - db
    depends_on:
      - db
    ports:
      - 80:3000
    volumes:
      - ./data/web:/var/lib/grafana
