---
version: "2"
services:
  db:
    build: ./db
    image: rcreasey/speedtest-meter:db-rpi
    ports:
      - 8083:8083
      - 8086:8086
    volumes:
      - ./data/db:/var/lib/influxdb
  probe:
    build: ./probe
    image: rcreasey/speedtest-meter:probe-rpi
    links:
      - db
    depends_on:
      - db
  web:
    build: ./web
    image: rcreasey/speedtest-meter:web-rpi
    links:
      - db
    depends_on:
      - db
    ports:
      - 80:3000
    volumes:
     - ./data/web:/var/lib/grafana
